version: '3' 
services:
  number:
    image: klayrocha-number-api:1.0 
    ports:
      - 9696:9696
    build:
      context: ./numbers-api/
      dockerfile: Dockerfile 
      
  country:
    image: klayrocha-country-api:1.0 
    ports:
      - 9797:9797
    build:
      context: ./country-api/
      dockerfile: Dockerfile